# config.py

CONFIG = {
    "MAX_PRIORITY_LEVELS": 32,
    "DEFAULT_BASE_CONTEXT_SWITCH_OVERHEAD": 0.1,
    "INTERRUPT_PROBABILITY": 0.05,
    "MAX_TEMPERATURE": 85.0,
    "MIN_FREQ": 0.4,
    "MAX_FREQ": 1.0,
}

# Constants derived from CONFIG or defined independently
DEFAULT_BASE_CONTEXT_SWITCH_OVERHEAD = CONFIG["DEFAULT_BASE_CONTEXT_SWITCH_OVERHEAD"]
INTERRUPT_PROBABILITY = CONFIG["INTERRUPT_PROBABILITY"]
MAX_PRIORITY_LEVELS = CONFIG["MAX_PRIORITY_LEVELS"]
MAX_TEMPERATURE = CONFIG["MAX_TEMPERATURE"]
MIN_FREQ = CONFIG["MIN_FREQ"]
MAX_FREQ = CONFIG["MAX_FREQ"]

# Additional constants not in CONFIG
SCHEDULER_OVERHEAD_FACTOR = 0.001
TEMPERATURE_DECAY = 0.05
LOAD_PREDICTION_WINDOW = 5